output "ec2_machines" {
  value =aws_instance.launch_ec2_instances.*.private_ip
}

resource "local_file" "hosts_cfg" {
  content = templatefile("hosts.tpl",
    {
      launch_ec2_instances  = aws_instance.launch_ec2_instances.*.private_ip
      usr = var.user
      pemkey = var.PemkeyName
    }
  )
  
   filename = "../ansible-scripts/hosts.ini"
}

# resource "local_file" "tf_ansible_vars_file_new" {
#   content = <<-DOC
#     # Ansible vars_file containing variable values from Terraform.
#     # Generated by Terraform mgmt configuration.

#     tf_pemkeyname: ${var.PemkeyName}
#    #tf_gitlab_backup_bucket_name: ${aws_s3_bucket.gitlab_backup.bucket}
#     DOC
#   filename = "../ansible-scripts/vars/main.yml"
# }
